### PR TITLE
Ported regex support from django-mssql

### PR DESCRIPTION
**Pull request by mrbean-bremen**

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
As I needed regex support, I ported this over from django-mssql half a year ago.
I did contact the maintainer, but got no response - the project seems to be unmaintained now (at least there has been no commit for more than a year now), so I decided to make a PR from this in case someone else needs it.

**Comment by mrbean-bremen** [comment]
Any chance to get this in, or shall I close it?
Note that [django-mssql](https://bitbucket.org/Manfre/django-mssql) is not maintained anymore, and the owner suggests to switch to django-pyodbc-azure.

**Comment by kevin-olbrich** [comment]
I have not tested your patch but I think, everything of value should be migrated from django-mssql to this package.

**Comment by mrbean-bremen** [comment]
I use this in production code, so far there have been no problems (currently with Python 3.6, Django 1.11).

**Comment by OskarPersson** [comment]
Where does the dll-file originate from? I'm thinking of adding regex support to [django-mssql-backend](https://github.com/ESSolutions/django-mssql-backend) (a fork of this repo) but I would like to understand of everything fits together first.

**Comment by mrbean-bremen** [comment]
I have taken this from django-mssql directly, but as far as I remember, I had also looked at the source code (which was Visual Basic iirc). I can try to dig this up later this week (traveling right now).

**Comment by mrbean-bremen** [comment]
@OskarPersson - you can find source code for a CLR DLL [here](https://www.red-gate.com/simple-talk/sql/t-sql-programming/clr-assembly-regex-functions-for-sql-server-by-example/), though I'm not sure if this was the source of the given DLL - the source code hadn't been provided at [django-mssql](https://bitbucket.org/Manfre/django-mssql/src/master/sqlserver_ado/regex_clr.dll).

**Comment by OskarPersson** [comment]
I've now created a PR with this in django-mssql-backend: https://github.com/ESSolutions/django-mssql-backend/pull/43

**Comment by mrbean-bremen** [comment]
Closing - repo is not maintained anymore.

**Pull request closed without merging**
