### PR TITLE
Uptick version for Django 1.10.

### PR DESCRIPTION
**Pull request by FlipperPA**
I've upped the version check for Django 1.10 and done some preliminary testing - it seems okay on the site I've tested.

### CODE REVIEW

**Comment by michiya** [comment]
@FlipperPA Thank you for the PR! I've pushed django-pyodbc-azure 1.10.0.0 to PyPI today and sorry that I couldn't merge the PR because I had to create a new branch for v1.10 and there were some more to be added to support Django 1.10 features. I hope that you enjoy the new version and any feedback is greatly appreciated as ever.

**Comment by mattbits** [comment]
python compares each element in truple. this breaks 1.9.6 since 6 > 0.
  File "/usr/local/lib/python2.7/site-packages/sql_server/pyodbc/base.py", line 11, in <module>
    raise ImproperlyConfigured("Django %d.%d.%d is not supported." % VERSION[:3])
django.core.exceptions.ImproperlyConfigured: Django 1.9.6 is not supported.
please rollback or correct.

**Comment by michiya** [comment]
@mattpetrick django-pyodbc-azure v1.10.0.0 only supports Django 1.10 (see Notice on README). You can use v1.9,6,0 for Django 1.9,6 instead, and v1.9.9.0 for Django 1.9.9 is also available on PyPI.

**Comment by mattbits** [comment]
@michiya thanks i do now see that after i gave my feedback a new branch was created. much appreciated!

**Pull request closed without merging**
